# To run in detached mode
# docker-compose -f environment/docker-compose.yml up -d

version: "3"

services:

  alerts-amazon-daily:
    image: terrabrasilis/amazon-alert-daily:v2.4
  
  alerts-amazon-aggregated:
    image: terrabrasilis/amazon-alert-aggregated:v2.4
